### PR TITLE
Icon perfection!

### PR DESCRIPTION
**Pull request by annr**
Icons we need to replace:

- [ ] info.svg
- [ ] leave.svg
- [ ] lock.svg
- [ ] mail.svg
- [ ] time.svg
- [ ] minus.svg

#### Pull request checklist
- [ ] UX Designer has approved visual changes

### CODE REVIEW

**Comment by adrianmg** [comment]
@annr I just added and fixed the icons mentioned in the list.

One thing to consider: we don't use 'down' icon anymore as we now have caretDown. Could you please remove the references to that one?

I couldn't run the build and check the visual diffs due an error I'm getting when the build process tries to run 'tsc-project'. Not sure what's related to but I also tried to 'yarn svg' and it doesn't seem to fix the issue (not sure if it's actually related).

image

**Comment by unindented** [comment]
@adrianmg I think `yarn svg` is missing the part that generates the `.tsx` files. That's why you're getting the error.

@annr can we add the script here in YamUI?

**Comment by annr** [comment]
I can make a separate PR with the tool after I update this branch with the files for Adrian.

**Comment by annr** [comment]
@adrianmg -- we need the icons not to have "xlink:href="#a"" in them. Manuel fixed the minus icon yesterday, I think by removing a mask. I know he's gone right now but maybe you can ask him what he did.

**Comment by adrianmg** [comment]
@annr would take a look tomorrow. I was assuming the plugin was also taking care of that, would take a look :)

**Pull request merged**
