### PR TITLE
Adding icon Filter

### PR DESCRIPTION
**Pull request by adrianmg**
Adding the Filter icon to the library.

## Pull request checklist

* [x] Component `README.md` file is up-to-date.
* [x] Component is unit tested.

@rese @mamuso

### CODE REVIEW

**Comment by unindented** [comment]
Can you also update this unit test to say 116? https://github.com/Microsoft/YamUI/blob/2364ebbfb2164b2024670d5d67d975a0cbd24cac/src/components/Icon/Icon.test.tsx#L66

**Comment by adrianmg** [comment]
Updated to 116

**Comment by rese** [comment]
Hi @mamuso, would you have time to review this PR?

**Comment by rese** [comment]
@mamuso and @richardtagger, could you please review? Thanks!

**Pull request merged**
