### PR TITLE
add icon label as class in the form 'yj-icon-label' in order to test …

### PR DESCRIPTION
**Pull request by annr**
Yamjs unit tests look for specific icons, but we don't currently pass that info.

### CODE REVIEW

**Comment by annr** [comment]
@unindented -- what do you think of this solution for preserving Yamjs unit tests?

**Comment by annr** [comment]
We probably want to do this in any case -- have a way to tell what icon it is from the markup, that is.

**Comment by unindented** [comment]
Yup, I think having an attribute indicate this is a good idea. Maybe not the class name, in case we ever mangle it, with something like CSS modules (https://github.com/webpack-contrib/css-loader#modules) or Fabric's `merge-styles` (https://github.com/OfficeDev/office-ui-fabric-react/tree/master/packages/merge-styles)? What about a `data-` attribute?

**Comment by annr** [comment]
What do you prefer? data-label or data-icon-label?

**Comment by annr** [comment]
or data-icon, data-icon-name... please choose or offer another.

**Comment by unindented** [comment]
`data-icon` sounds good to me.

**Pull request merged**
