### PR TITLE
Added new Send icon

### PR DESCRIPTION
**Pull request by adrianmg**
Adding a new icon 'Send' for Townhall (it's coming from Fabric icon set).

It needs @mamuso review to validate visual diff changes

### CODE REVIEW

**Comment by adrianmg** [comment]
@mrfunkycold

**Comment by unindented** [comment]
I think the `assets/icons` folder in this repo is lowercase, but your local folder is uppercase (GitHub says you're adding `assets/Icons/Send.svg`).

@adrianmg could you try running `git mv assets/Icons/Send.svg assets/icons/Send.svg`?

**Comment by mamuso** [comment]
@adrianmg @unindented I moved the icon and generated the preview

**Comment by adrianmg** [comment]
That's weird… I already saw the 'Icons' case once in the past but I just created one clean branch from scratch. Not sure what happened there, sorry about that!

**Comment by unindented** [comment]
@adrianmg No worries!

**Comment by mrfunkycold** [comment]
@unindented @adrianmg is there anything in particular that needs to happen to this PR?

**Comment by unindented** [comment]
Sounds like you need to update the reference screenshot.

**Comment by mrfunkycold** [comment]
Thanks working on updating this PR.

**Comment by mrfunkycold** [comment]
@adrianmg @mamuso @unindented @swese44 updated the asset let me know if there is anything else.

**Comment by mrfunkycold** [comment]
heads up @alxHenry

**Comment by alxHenry** [comment]
Merge killed my unit test. Updating the like button PR and waiting for travis. Is this unit test necessary?

**Pull request merged**
