### PR TITLE
Fabric upgrade to reduce bundle

### PR DESCRIPTION
**Pull request by annr**
This PR is ready. However, we probably want to wait to merge https://github.com/Microsoft/YamUI/pull/61 to master first so that I get the conflicts, not @bryan-gislason.

### CODE REVIEW

**Comment by unindented** [comment]
Awesome work. I wasn't expecting this to go so smoothly. The 100% test coverage and the visual diffs also give me a ton of confidence.

**Comment by unindented** [comment]
The missing caret for dropdowns is related to Fabric pulling out their icons right?

**Comment by bryan-gislason** [comment]
@unindented: Probably, looks like this is mentioned here i think: https://github.com/OfficeDev/office-ui-fabric-react/issues/2967#issuecomment-332659624

**Comment by unindented** [comment]
Confirmed then.

**Comment by unindented** [comment]
This PR can be closed now right?

**Pull request closed without merging**
