### PR TITLE
Rename Callout to Hovercard

### PR DESCRIPTION
**Pull request by swese44**
I'll follow this with another change to extract our Callout component from Hovercard.

Lots of changes but just a rename. Not sure why unrelated visual diff image files are getting updated, there aren't actually visual changes to them.

## Pull request checklist

* [x] Component `README.md` file is up-to-date.
* [x] Component is unit tested.

### CODE REVIEW

**Comment by unindented** [comment]
Those reference files you've added... Are they related to examples you renamed/deleted? If so, you should delete them from your folder too, and remove them from this PR.

**Comment by swese44** [comment]
@unindented do we know why the reference images are changing without visual changes? does puppeteer add any file metadata which may change?

**Comment by swese44** [comment]
would it be better to leave the changed images in this PR so they don't change in other upcoming PRs?

**Comment by swese44** [comment]
oh nevermind, they've resolved themselves after syncing from master. only Callout/Hovercard diffs are left

**Comment by unindented** [comment]
I have no idea why Git didn't pick it up as a move. You could try a `git mv` of the old reference files to the new names, and see if that causes any diffs?

**Comment by swese44** [comment]
all good, resolved after syncing from master

**Comment by adrianmg** [comment]
LGTM
image

**Pull request merged**
