### PR TITLE
Adding LikeFull icon to the library

### PR DESCRIPTION
**Pull request by mamuso**

### CODE REVIEW

**Comment by unindented** [comment]
Uh oh, uppercase `Icons` folder strikes again:

screen shot 2018-02-27 at 6 06 28 pm

Can you make sure your folder is lowercase, and also run `git move assets/Icons/LikeSolid.svg assets/icons/LikeSolid.svg`?

**Comment by swese44** [comment]
@mamuso i pushed a commit to fix a test which verifies the total number of icons, you'll need to pull that change when you fix the capitalized "Icons" folder :)

**Comment by alxHenry** [comment]
@mrfunkycold this is the like icon pr

**Comment by alxHenry** [comment]
@swese44 can you sign off on this

**Comment by swese44** [comment]
still need signoff from @adrianmg

**Comment by alxHenry** [comment]
@adrianmg @mamuso I picked up Manuel's PR and fixed the issue on the like button folder. Would you mind signing off?

**Pull request merged**
