### PR TITLE
[MediaObject] Use ellipsis for text

### PR DESCRIPTION
**Pull request by richardtagger**
Text contents should not flow to next line if too long for width of container

## Pull request checklist

* [x] Component `README.md` file is up-to-date.
* [x] Component is unit tested.

### CODE REVIEW

**Comment by richardtagger** [comment]
@unindented

**Comment by unindented** [comment]
Should the same apply for meta and extra?

**Comment by richardtagger** [comment]
done

**Comment by swese44** [comment]
was this requested by UX? please add long examples with visual diffs, UX should sign off on these visual changes

**Comment by richardtagger** [comment]
nope - just looks weird.  I asumed this content was always intended to be a single line. e.g. 
screen shot 2017-12-25 at 12 07 35 am
screen shot 2017-12-24 at 4 00 13 pm

**Comment by swese44** [comment]
there are examples of MediaObject here which don't use ellipsis
https://app.zeplin.io/project/5907d6451d2b06c6b36b2852/screen/59c582c900581ab06b104f2f

**Comment by swese44** [comment]
ya please check with UX before merging, i'm not sure what the visual requirements are. it may be better to default to ellipsis text for title and/or subtexts, but still allow a prop like `allowWrappedText`

**Comment by richardtagger** [comment]
are the recent activities meant to be MediaObjects too? so this should be a prop?

**Comment by swese44** [comment]
i don't know. @mamuso or @adrianmg could you provide UX requirements on if/when MediaObject title or subtexts should wrap or use ellipsis? thanks!

either way let's add examples with visual diffs to make sure we don't accidentally break this in the future

**Comment by richardtagger** [comment]
I've added an example - if it's determined we need to support wrapping lines down the road that's an easy prop to add. Currently nothing consumes MediaObject - I'll be the first and most use cases from Zeplin seem to be single line.

**Comment by mamuso** [comment]
If we are not repurposing media objects for other cases, then they should handle the ellipsis

**Comment by swese44** [comment]
sweet thanks @richardtagger. we can always add a prop if we need to extend MediaObject and allow wrapping

**Pull request merged**
