### PR TITLE
feat(ActionLink): Add ActionLink component

### PR DESCRIPTION
**Pull request by allobast**
Adding ActionLink component
screen shot 2018-05-10 at 2 34 11 pm
Spec: https://www.yammer.com/microsoft.com/uploaded_files/133473754/edit
## Pull request checklist

* [x] Component `README.md` file is up-to-date.
* [x] Component is unit tested.

### CODE REVIEW

**Comment by allobast** [comment]
@swese44

**Comment by swese44** [comment]
hey @BrendanMcK we're currently stuffing the `ariaLabel` prop into `NavigationLink`'s `title` attribute here. should we instead support `ariaLabel` on `NavigationLink`?

**Comment by swese44** [comment]
fixed the ellipsis issue. it worked for Link but Clickable version needed block={true}. added some more examples for visual test coverage there.

also updated paddings to get the overall dimensions to match the mockups

**Comment by swese44** [comment]
@BrendanMcK, @allobast has moved ariaLabel to NavigationLink's ariaLabel attribute

**Pull request merged**
