### PR TITLE
Support tree-shaking by adding a es2015 build target

### PR DESCRIPTION
**Pull request by a-tarasyuk**
[Microsoft/YamUI#274](https://github.com/Microsoft/YamUI/issues/274)

### CODE REVIEW

**Comment by swese44** [comment]
hey thanks @a-tarasyuk. there are also CSS build steps which use postcss to build global and component CSS artifacts in the build directory, these steps would also need to copy their contents to the new build directory.

hey @unindented, any ideas for validating the build output in each directory?

**Comment by a-tarasyuk** [comment]
@swese44 Thanks, will add.

**Comment by a-tarasyuk** [comment]
@swese44 Which `node`/`npm` versions do you use? I see that `package-lock.json` contains many changes, however, only one package was installed. When I switch to `master` and run `npm i` -  `package-lock.json` also updates, I suppose we use different node/npm versions.

**Comment by swese44** [comment]
@a-tarasyuk i'm on node 8.8.1 and npm 5.4.2 at the moment. it looks like jest (at least in the YamUI repo) has issues on node 10.0.0, i haven't investigated why yet

**Comment by swese44** [comment]
ah bad timing :) we've decided to support es6 modules directly instead of an alternate build target:
https://github.com/Microsoft/YamUI/issues/274#issuecomment-387909239

@a-tarasyuk we'd love to still have you as a contributor. if you want to close this PR and open a new one with a commit to support es6 modules in the default `tsconfig.json` file i can build on that and integrate the newer version of Fabric

**Comment by a-tarasyuk** [comment]
@swese44 ok, thanks

**Pull request closed without merging**
