### PR TITLE
Adding all the document icons

### PR DESCRIPTION
**Pull request by mamuso**
Adding ODSP document icons

### CODE REVIEW

**Comment by unindented** [comment]
@mamuso Are these optimized in any way? I'm seeing Illustrator comments in there, which probably means they haven't gone through SVGO.

**Comment by unindented** [comment]
@mamuso ah, nevermind. It's our tasks that are the problem, we're only reading from the `icons` folder.

**Comment by mamuso** [comment]
@jessemartin is going to need this for his project. @unindented, @swese44, @richardtagger what would be the best way to move this component forward?

**Comment by unindented** [comment]
@mamuso this PR has everything green, so feel free to press the button.

If Townhall needs the component, @jessemartin can probably pair with P.J. or I to implement it.

**Pull request merged**
