### PR TITLE
Update dependencies to latest version where possible

### PR DESCRIPTION
**Pull request by unindented**
Just wanted latest Fabric, but heck, I might as well update dev dependencies while I'm at it.

Had to leave out:
- ~`webpack`: cause Storybook is still on 3~ Ugh, we use Styleguidist here, nevermind
- ~`ts-loader`: cause latest `ts-loader` isn't compatible with Webpack 3~ Same
- `react-intersection-observer`: cause it introduces type issues I couldn't resolve easily

### CODE REVIEW

**Comment by chrismohr** [comment]
Just curious, what command did you use to do this?  Did you use `npm-check-updates`?

**Comment by unindented** [comment]
Yup, `npm-check-updates`.

**Comment by chrismohr** [comment]
You mentioned `Storybook` above, I'm guessing you meant `Styleguidist`?

**Comment by unindented** [comment]
Gaah lots of visual diffs, abort, abort!

**Comment by unindented** [comment]
@chrismohr LOL I forgot we use Styleguidist here, which is on Webpack 4, so nothing I said applies.

The visual diffs are a problem though.

**Comment by unindented** [comment]
Running visual diffs locally just with the Fabric bump, see what happens.

**Comment by unindented** [comment]
Just Fabric bump is fine, so I'll close this PR and open a new one.

**Pull request closed without merging**
