### PR TITLE
[SuggestionsList] Change mouseOut to mouseLeave

### PR DESCRIPTION
**Pull request by richardtagger**
Mouse out causes flickering

* [x] Component `README.md` file is up-to-date.
* [x] Component is unit tested.

### CODE REVIEW

**Comment by unindented** [comment]
Why does it produce flickering? Can you detail? I think @swese44 was originally concerned about `onMouseOver` because of the amount of events we'd generate. Can you record the React Dev Tools with *Highlight Updates* enabled, so that we see what we're re-rendering atm?

**Comment by richardtagger** [comment]
YamJS branchname `editor-container` has it for you to have a look

**Comment by unindented** [comment]
Could you record with Quicktime and post on Yammer? Or create a GIF and post here? I'm a bit swamped with PRs.

**Comment by swese44** [comment]
sorry i was actually not working on my vacation. this change is correct, onMouseLeave matches the onMouseEnter event which we're also using

**Pull request merged**
