### PR TITLE
Update linting rules across the codebase

### PR DESCRIPTION
**Pull request by swese44**
- Updates tslint and eslint rules to match our modern project
- Updates the necessary dependencies
- Updates Jest config for Enzyme@3
- Updates tests to handle Enzyme@3 API changes
- Fixes all linting issues
- Updates SVG template for new linting rules, and re-generated Icon components
- Adds prettier+husky to auto format files precommit
- Removes core-decorators and autobind

## Pull request checklist

* [x] Component `README.md` file is up-to-date.
* [x] Component is unit tested.

### CODE REVIEW

**Comment by unindented** [comment]
Scrolled a bit, it looks good. We can rely on unit tests + visual diffs.

**Comment by swese44** [comment]
i'll work on getting @jessemartin's PR out first
https://github.com/Microsoft/YamUI/pull/280

**Comment by jessemartin** [comment]
Sorry about the config conflicts. If you'd like to pair to resolve them, let me know.

**Comment by swese44** [comment]
@jessemartin all good, i was expecting them

**Pull request merged**
